# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='attachments')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nominal', models.CharField(max_length=255)),
                ('order_index', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=500, upload_to='event/image')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=19)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True)),
                ('is_active', models.BooleanField()),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('businness_types', models.ManyToManyField(blank=True, null=True, to='company.Businnes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('company_product_or_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProductOrService')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='EventAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, max_digits=19)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Currency')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventAppealResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ative', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Event', unique=True)),
                ('eventappeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.EventAppeal')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, max_digits=19)),
                ('is_pay', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Currency')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=19)),
                ('active', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_product_or_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProductOrService')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Currency')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='attachmentevent',
            name='event_appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.EventAppeal'),
        ),
        migrations.AlterUniqueTogether(
            name='eventappeal',
            unique_together=set([('event', 'company')]),
        ),
    ]
