# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True),
        ),
    ]
