from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *

urlpatterns = [
    url(r'^profile/$', dashboard, name='dashboard'),
    url(r'^profile/admin-details-data-change-section/(?P<content_slug>[\w-]+)/$', admin_details_data_change_section, name='admin_details_data_change_section'),
    url(r'^profile/admin-details-data-change-section/(?P<content_slug>[\w-]+)/profile/(?P<p_id>[\w-]+)/$', admin_profile_details_changed_data_confirm, name='admin_profile_details_changed_data_confirm'),
    url(r'^profile/admin-content-section/(?P<content_slug>[\w-]+)/(?P<a_slug>[\w-]+)/$', admin_content_section, name='admin_content_section'),
    url(r'^profile/admin-content-section/(?P<content_slug>[\w-]+)/company/(?P<c_id>[\w-]+)/$', admin_company_page, name='admin_company_page'),
    url(r'^profile/admin-content-section/(?P<content_slug>[\w-]+)/profile/(?P<p_id>[\w-]+)/$', admin_profile_page, name='admin_profile_page'),
    url(r'^profile/notifications/$', notifications, name='notifications'),
    url(r'^profile/change-password/$', change_password, name='change_password'),
    url(r'^profile/change-change_photo/$', change_photo, name='change_photo'),
    url(r'^profile/change-change-profile-data/(?P<e_slug>[\w-]+)/$', change_profile_data, name='change_profile_data'),
    # url(r'^profile/choose-company/create-product-or-service/$', create_product_service_redirect, name='create_product_service_redirect'),
    url(r'^profile/choose-company/(?P<action_slug>[\w-]+)-product-or-service/$', product_service_redirect,
        name='product_service_redirect'),
    url(r'^profile/choose-company-event/(?P<action_slug>[\w-]+)/$', event_redirect, name='event_redirect'),
    url(r'^profile/choose-company-event/$', company_request_event_appeal_redirect, name='company_request_event_appeal_redirect'),
    url(r'^profile/my-events/$', my_events, name='my_events'),
    url(r'^profile/my-events/company/(?P<c_id>[\w-]+)/$', my_company_events, name='my_company_events'),
    url(r'^profile/request/my-events/company/(?P<c_id>[\w-]+)/$', my_company_request_events, name='my_company_request_events'),
    url(r'^profile/my-events/company/(?P<c_id>[\w-]+)/create/$', event_create, name='event_create'),
    url(r'^profile/my-events/company/(?P<c_id>[\w-]+)/edit/(?P<e_id>[0-9]+)/$', event_edit, name='event_edit'),
    # url(r'^profile/my-events/company/(?P<c_id>[\w-]+)/delete/(?P<e_id>[0-9]+)/$', deleted_event, name='deleted_event'),
    url(r'^profile/my-events/company/(?P<c_id>[\w-]+)/appeals/(?P<e_id>[0-9]+)/$', my_company_event_appeals,
        name='my_company_event_appeals'),
    url(r'^profile/confirm/my-events/company/(?P<c_id>[\w-]+)/appeals/(?P<e_id>[0-9]+)/(?P<ae_id>[0-9]+)/$', my_company_event_appeal_confirm,
        name='my_company_event_appeal_confirm'),
    url(r'^profile/create/pr-product-or-service/$', pr_create_product_or_service, name='pr_create_product_or_service'),
    url(r'^profile/companies/$', my_companies, name='my_companies'),
    url(r'^profile/companies/deleted-company/(?P<c_id>[\w-]+)/$', deleted_company, name='deleted_company'),
    url(r'^profile/companies/deleted-event/(?P<e_id>[0-9]+)/$', deleted_event, name='deleted_event'),
    url(r'^profile/company/(?P<c_id>[\w-]+)/$', my_company, name='my_company'),
    url(r'^profile/recycle-bin/content/(?P<content_slug>[\w-]+)/$', recycle_bin, name='recycle_bin'),
    url(r'^profile/add/company/$', create_company, name='create_company'),
    url(r'^profile/edit/company/(?P<c_id>[\w-]+)/$', edit_company, name='edit_company'),
    # url(r'^profile/company/(?P<c_id>[\w-]+)/tenders/$', my_company_tenders, name='my_company_tenders'),
    url(r'^profile/company/product-or-service/list/(?P<company_id>[\w-]+)/$', list_product_service,
        name='list_product_service'),
    url(r'^profile/company/product-or-service/delete/(?P<ps_id>[\w-]+)/$', deleted_product_or_service,
        name='deleted_product_or_service'),
    url(r'^profile/company/product-or-service/add/(?P<company_id>[\w-]+)/$', create_product_service,
        name='create_product_service'),
    url(r'^profile/company/product-or-service/edit/(?P<company_id>[\w-]+)/(?P<cp_id>[\w-]+)/$', edit_product_service,
        name='edit_product_service'),
    url(r'^profile/company/product/(?P<cp_id>[\w-]+)/preview/$', company_product_or_service_preview, name='company_product_or_service_preview'),
    # url(r'^contact/$', 'home.views.contact',name='contact'),

    url(r'^profile/parent-business-ajax/$', profile_parent_business_ajax, name='profile_parent_business_ajax'),
    url(r'^profile/parent-business-year-ajax/$', profile_parent_business_year_ajax, name='profile_parent_business_year_ajax'),
    url(r'^profile/chart-now-year-month-ajax/$', chart_now_year_month_ajax, name='chart_now_year_month_ajax'),
    url(r'^chart-business-ajax/$', chart_business_ajax, name='chart_business_ajax'),
    url(r'^profile/wish-list/$', profile_wish_list, name='profile_wish_list'),
    url(r'^profile/products-buy-list/$', profile_products_buy_list, name='profile_products_buy_list'),
]
