# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-20 14:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_photos')),
                ('type', models.CharField(choices=[('admin-person', 'admin_person'), ('juridical-person', 'juridical_person'), ('individual-person', 'individual_person'), ('ordinary-person', 'ordinary_person')], default='juridical-person', max_length=100)),
                ('status', models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('widow', 'Widow')], max_length=100, null=True)),
                ('voen', models.CharField(blank=True, max_length=255)),
                ('bank_account', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('practices', models.TextField()),
                ('activation_key', models.CharField(blank=True, editable=False, max_length=40)),
                ('reset_token_key', models.CharField(blank=True, editable=False, max_length=40)),
                ('key_expires', models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 20, 14, 18, 21, 118933, tzinfo=utc), editable=False, null=True)),
                ('reset_key_expires', models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 20, 14, 18, 21, 118933, tzinfo=utc), editable=False, null=True)),
                ('businnes_type', models.ManyToManyField(to='company.Businnes')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
