# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-02 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170621_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 2, 13, 5, 45, 544004, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 2, 13, 5, 45, 544004, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('married', 'Evli'), ('single', 'Subay'), ('widow', 'Dul')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('admin-person', 'Admin profili'), ('juridical-person', 'Hüquqi şəxs'), ('individual-person', 'Fiziki şəxs'), ('ordinary-person', 'Adi şəxs')], default='juridical-person', max_length=100),
        ),
    ]
