# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-06 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170702_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 6, 8, 16, 13, 898252, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 6, 8, 16, 13, 898252, tzinfo=utc), editable=False, null=True),
        ),
    ]
