# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('company', '0006_auto_20170708_1619'),
        ('registration', '0004_auto_20170706_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('juridical-person', 'juridical_person'), ('individual-person', 'individual_person'), ('ordinary-person', 'ordinary_person')], default='juridical-person', max_length=100)),
                ('voen', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('practices', models.TextField()),
                ('admin_confirm', models.BooleanField(default=False)),
                ('businnes_type', models.ManyToManyField(to='company.Businnes')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Region')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 12, 19, 45, 630687, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 12, 19, 45, 630687, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('widow', 'Widow')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('admin-person', 'admin_person'), ('juridical-person', 'juridical_person'), ('individual-person', 'individual_person'), ('ordinary-person', 'ordinary_person')], default='juridical-person', max_length=100),
        ),
    ]
