# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20170708_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeprofile',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 8, 12, 26, 31, 11316, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changeprofile',
            name='profile',
            field=models.ForeignKey(default=datetime.datetime(2017, 7, 8, 12, 26, 55, 280589, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='registration.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changeprofile',
            name='businnes_type',
            field=models.ManyToManyField(blank=True, null=True, to='company.Businnes'),
        ),
        migrations.AlterField(
            model_name='changeprofile',
            name='practices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 12, 26, 11, 678902, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 12, 26, 11, 678902, tzinfo=utc), editable=False, null=True),
        ),
    ]
