# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20170708_1758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChangeProfile',
            new_name='ChangeProfileInfo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 14, 0, 0, 15203, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 14, 0, 0, 15203, tzinfo=utc), editable=False, null=True),
        ),
    ]
