# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20170708_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeprofileinfo',
            name='businnes_type',
        ),
        migrations.RemoveField(
            model_name='changeprofileinfo',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='changeprofileinfo',
            name='region',
        ),
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 14, 0, 24, 168656, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 14, 0, 24, 168656, tzinfo=utc), editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='ChangeProfileInfo',
        ),
    ]
