# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20170708_1804'),
        ('general', '0001_initial'),
        ('registration', '0010_auto_20170708_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('juridical-person', 'juridical_person'), ('individual-person', 'individual_person'), ('ordinary-person', 'ordinary_person')], default='juridical-person', max_length=100)),
                ('voen', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('practices', models.TextField(blank=True, null=True)),
                ('admin_confirm', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('businnes_type', models.ManyToManyField(blank=True, null=True, to='company.Businnes')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 14, 4, 11, 912693, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 14, 4, 11, 912693, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AddField(
            model_name='changeprofileinfo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile'),
        ),
        migrations.AddField(
            model_name='changeprofileinfo',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Region'),
        ),
    ]
