# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20170709_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeprofileinfo',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 11, 11, 34, 5, 902253, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='practices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 11, 11, 34, 5, 902253, tzinfo=utc), editable=False, null=True),
        ),
    ]
