# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-12 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20170711_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 12, 13, 32, 20, 329209, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 12, 13, 32, 20, 329209, tzinfo=utc), editable=False, null=True),
        ),
    ]
