# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-20 14:18
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('active', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_product_or_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProductOrService')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('home1_ads_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home1_ads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('home1_ads_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('home1_ads_context', models.TextField(blank=True, null=True)),
                ('home1_ads_active', models.BooleanField()),
                ('home2_ads_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home2_ads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('home2_ads_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('home2_ads_context', models.TextField(blank=True, null=True)),
                ('home2_ads_active', models.BooleanField()),
                ('home3_ads_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home3_ads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('home3_ads_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('home3_ads_context', models.TextField(blank=True, null=True)),
                ('home3_ads_active', models.BooleanField()),
                ('home4_ads_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home4_ads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('home4_ads_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('home4_ads_context', models.TextField(blank=True, null=True)),
                ('home4_ads_active', models.BooleanField()),
                ('home5_ads_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home5_ads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('home5_ads_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('home5_ads_context', models.TextField(blank=True, null=True)),
                ('home5_ads_active', models.BooleanField()),
                ('product_detail1_ads_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_detail1_ads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('product_detail1_ads_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('product_detail1_ads_context', models.TextField(blank=True, null=True)),
                ('product_detail1_ads_active', models.BooleanField(default=False)),
                ('product_detail2_ads_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_detail2_ads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('product_detail2_ads_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('product_detail2_ads_context', models.TextField(blank=True, null=True)),
                ('product_detail2_ads_active', models.BooleanField(default=False)),
                ('event_detail1_ads_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_detail1_ads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('event_detail1_ads_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('event_detail1_ads_context', models.TextField(blank=True, null=True)),
                ('event_detail1_ads_active', models.BooleanField(default=False)),
                ('event_detail2_ads_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_detail2_ads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('event_detail2_ads_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('event_detail2_ads_context', models.TextField(blank=True, null=True)),
                ('event_detail2_ads_active', models.BooleanField(default=False)),
                ('search1_ads_name', models.CharField(blank=True, max_length=255, null=True)),
                ('search1_ads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('search1_ads_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('search1_ads_context', models.TextField(blank=True, null=True)),
                ('search1_ads_active', models.BooleanField(default=False)),
                ('search2_ads_name', models.CharField(blank=True, max_length=255, null=True)),
                ('search2_ads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('search2_ads_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('search2_ads_context', models.TextField(blank=True, null=True)),
                ('search2_ads_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('main_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('main_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('main_address', models.CharField(blank=True, max_length=255, null=True)),
                ('services_about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('social_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='company-info/social-image')),
                ('active', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=19)),
                ('difference', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True)),
                ('order_index', models.IntegerField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Valyuta',
                'verbose_name': 'valyuta',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('context', ckeditor_uploader.fields.RichTextUploadingField()),
                ('order_index', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(max_length=500, upload_to='partner')),
                ('url', models.URLField()),
                ('order_index', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_text', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('order_index', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('fb', 'Facebook_Color'), ('tw', 'Twitter_Color'), ('googleplus', 'Googleplus_Color'), ('rss', 'Rss_Color'), ('pintrest', 'Pintrest_Color'), ('linkedin', 'Linkedin_Color'), ('youtube', 'Youtube_Color')], max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('order_index', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('new_blank', models.BooleanField(default=False)),
                ('order_index', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_product_or_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProductOrService')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
