# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170702_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='color',
            field=models.CharField(choices=[('fb', 'Facebook_Color'), ('tw', 'Twitter_Color'), ('googleplus', 'Googleplus_Color'), ('rss', 'Rss_Color'), ('pintrest', 'Pintrest_Color'), ('linkedin', 'Linkedin_Color'), ('youtube', 'Youtube_Color')], max_length=255),
        ),
    ]
