# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('payment', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_product_or_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProductOrService')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile')),
            ],
        ),
    ]
