# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-20 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import geoposition.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businnes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='fa fa-sitemap', max_length=255)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='business/images')),
                ('cover', models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='business/cover')),
                ('order_index', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(max_length=500, upload_to='companies/logo')),
                ('cover_photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='companies/cover-photo')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phones', models.CharField(blank=True, max_length=255, null=True)),
                ('voen', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('practices', models.TextField()),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('slug', models.SlugField(default='slug')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProductOrService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('product', 'product'), ('service', 'service')], default='product', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(max_length=500, upload_to='companies/logo')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=19)),
                ('price', models.DecimalField(decimal_places=5, max_digits=19)),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('deleted', models.BooleanField(default=False)),
                ('created_date', models.DateField(default=datetime.datetime(2017, 6, 20, 14, 18, 21, 96921, tzinfo=utc))),
                ('date', models.DateField(auto_now_add=True)),
                ('businness_types', models.ManyToManyField(blank=True, null=True, to='company.Businnes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProductOrServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='company_product-or-service/images', verbose_name='CompanyProductOrServiceImage')),
                ('company_product_or_service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProductOrService')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
