# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('general', '0001_initial'),
        ('payment', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproductorservice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Currency'),
        ),
        migrations.AddField(
            model_name='companyproductorservice',
            name='product_or_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ProductOrService'),
        ),
        migrations.AddField(
            model_name='company',
            name='businnes_type',
            field=models.ManyToManyField(to='company.Businnes'),
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile'),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Region'),
        ),
        migrations.AddField(
            model_name='businnes',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Businnes'),
        ),
    ]
