# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170620_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproductorservice',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 21, 6, 50, 26, 743953, tzinfo=utc)),
        ),
    ]
