# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-02 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20170621_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='company/attachments')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='companyproductorservice',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 2, 13, 5, 45, 512481, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='companyproductorservice',
            name='type',
            field=models.CharField(choices=[('product', 'Məhsul'), ('service', 'Xidmət')], default='product', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyproductorserviceimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='company_product-or-service/images', verbose_name='Məhsul və Xidmət Şəkli'),
        ),
    ]
