# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-06 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20170702_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproductorservice',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 6, 8, 16, 13, 868231, tzinfo=utc)),
        ),
    ]
