# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20170706_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproductorservice',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 8, 12, 19, 45, 582652, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='companyproductorservice',
            name='type',
            field=models.CharField(choices=[('product', 'product'), ('service', 'service')], default='product', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyproductorserviceimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='company_product-or-service/images', verbose_name='CompanyProductOrServiceImage'),
        ),
    ]
