# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20170709_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproductorservice',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 11, 11, 34, 5, 880256, tzinfo=utc)),
        ),
    ]
