# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-12 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20170711_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproductorservice',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 12, 13, 32, 20, 307194, tzinfo=utc)),
        ),
    ]
